/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAbout: typeof import('./src/components/base/AAbout.vue')['default']
    AbAnimatedPlaceholder: typeof import('./src/components/utils/AbAnimatedPlaceholder.vue')['default']
    AbCard: typeof import('./src/components/utils/AbCard.vue')['default']
    AbCardSkeleton: typeof import('./src/components/utils/AbCardSkeleton.vue')['default']
    AbDarkMode: typeof import('./src/components/utils/AbDarkMode.vue')['default']
    AbHamburger: typeof import('./src/components/utils/AbHamburger.vue')['default']
    AbTextModel: typeof import('./src/components/utils/AbTextModel.vue')['default']
    AbToast: typeof import('./src/components/utils/AbToast.vue')['default']
    AbTypewriter: typeof import('./src/components/utils/AbTypewriter.vue')['default']
    AContact: typeof import('./src/components/base/AContact.vue')['default']
    AFooter: typeof import('./src/components/base/AFooter.vue')['default']
    ANav: typeof import('./src/components/base/ANav.vue')['default']
    AServices: typeof import('./src/components/base/AServices.vue')['default']
    ASkills: typeof import('./src/components/base/ASkills.vue')['default']
    AWorks: typeof import('./src/components/base/AWorks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
